apiVersion: v1
kind: Service
metadata:
  name: nodeport-jorge-alvarez
  namespace: namespace-jorge-alvarez
spec:
  type: NodePort
  selector: 
    app: httpd
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
  