apiVersion: v1
kind: Service
metadata:
  name: servicio-jorge-alvarez
  namespace: namespace-jorge-alvarez
spec:
  selector:
    app: httpd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  